version: '3.7'

services:
    web:
        build: ./app/
        volumes:
            - ./app/:/usr/src/app/
        stdin_open: true
        ports:
            - 3001:3000
        depends_on: 
            - api
        environment: 
            - REACT_APP_API_BASE_URL=http://localhost:8081
            - NODE_ENV=development
    api:
        build: ./api/
        depends_on:
            - db
        ports:
            - 8081:8090
        environment: 
            - POSTGRES_HOST=db
            - POSTGRES_DATABASE_NAME=test
        secrets:
            - POSTGRES_USER
            - POSTGRES_PASSWORD

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment: 
            - PGADMIN_DEFAULT_EMAIL=thomas.guillouet@outlook.com
            - PGADMIN_DEFAULT_PASSWORD=17tg11J59
        depends_on:
            - db
        ports:
          - 8080:80

    db:
        image: postgres
        volumes:
            - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
        environment: 
            - POSTGRES_DB=test
            - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
            - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
        secrets:
            - POSTGRES_USER
            - POSTGRES_PASSWORD

secrets:
    POSTGRES_USER:
        file: ./secrets/user
    POSTGRES_PASSWORD:
        file: ./secrets/password