version: '3.7'

services:
    api:
        build: ./api/
        links:
            - db
        ports:
            - 8081:8090
        environment: 
            - POSTGRES_HOST=db
            - POSTGRES_DATABASE_NAME=test
        secrets:
            - POSTGRES_USER
            - POSTGRES_PASSWORD

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment: 
            - PGADMIN_DEFAULT_EMAIL=thomas.guillouet@outlook.com
            - PGADMIN_DEFAULT_PASSWORD=17tg11J59
        links:
            - db
        ports:
          - 8080:80

    db:
        image: postgres
        restart: always
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
            - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
        secrets:
            - POSTGRES_USER
            - POSTGRES_PASSWORD

secrets:
    POSTGRES_USER:
        file: ./secrets/user
    POSTGRES_PASSWORD:
        file: ./secrets/password